DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS fts;

DROP INDEX IF EXISTS idx_label;
DROP INDEX IF EXISTS idx_ift;
DROP INDEX IF EXISTS idx_edges_from;
DROP INDEX IF EXISTS idx_edges_to;
DROP INDEX IF EXISTS idx_edges_flt;

DROP TRIGGER IF EXISTS after_items_update
DROP TRIGGER IF EXISTS items_fts_insert;
DROP TRIGGER IF EXISTS items_after_delete;