DROP TABLE IF EXISTS nodes;
DROP TRIGGER IF EXISTS nodes_id_not_zero;
DROP INDEX IF EXISTS idx_nodes_name;
DROP TABLE IF EXISTS edges;
DROP INDEX IF EXISTS idx_edges_name;
DROP TABLE IF EXISTS edge_connections;
DROP INDEX IF EXISTS idx_edge_connections_edge_id;
DROP INDEX IF EXISTS idx_edge_connections_from_node_id;
DROP INDEX IF EXISTS idx_edge_connections_to_node_id;
