CREATE TABLE IF NOT EXISTS nodes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  properties JSONB NOT NULL DEFAULT '{}'::jsonb
);


CREATE TABLE IF NOT EXISTS edges (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  from_id INTEGER REFERENCES nodes(id),
  to_id INTEGER REFERENCES nodes(id),
  weight INTEGER DEFAULT 0,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb
);


CREATE TABLE IF NOT EXISTS node_labels (
  name TEXT NOT NULL,
  id REFERENCES nodes(id)
);


CREATE TABLE IF NOT EXISTS edge_labels (
  name TEXT NOT NULL,
  id REFERENCES edges(id)
);


CREATE TABLE IF NOT EXISTS outbox (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  topic TEXT NOT NULL,
  event TEXT NOT NULL DEFAULT CHECK (event IN ('insert', 'update', 'delete')),
  msg JSONB NOT NULL DEFAULT '{}'::jsonb
)


CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trg_update_node_timestamp
BEFORE UPDATE ON nodes
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();


CREATE TRIGGER trg_update_edge_timestamp
BEFORE UPDATE ON edges
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
