CREATE TABLE IF NOT EXISTS nodes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  properties JSONB NOT NULL DEFAULT '{}'::jsonb
);


CREATE TABLE IF NOT EXISTS edges (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  from_id INTEGER REFERENCES nodes(id),
  to_id INTEGER REFERENCES nodes(id),
  weight INTEGER DEFAULT 0,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb
);


CREATE INDEX IF EXISTS idx_edges_from_id ON edges (from_id);
CREATE INDEX IF EXISTS idx_edges_to_id ON edges (to_id);
CREATE INDEX IF EXISTS idx_edges ON edges (from_id, to_id);


CREATE TABLE IF NOT EXISTS node_labels (
  name TEXT NOT NULL,
  id REFERENCES nodes(id)
);


CREATE INDEX IF EXISTS idx_nodes_labels ON node_labels (name);


CREATE TABLE IF NOT EXISTS edge_labels (
  name TEXT NOT NULL,
  id REFERENCES edges(id)
);


CREATE INDEX IF EXISTS idx_edges_labels ON edge_labels (name);


CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trg_update_node_timestamp
BEFORE UPDATE ON nodes
FOR EACH ROW EXECUTE FUNCTION update_timestamp();


CREATE TRIGGER trg_update_edge_timestamp
BEFORE UPDATE ON edges
FOR EACH ROW EXECUTE FUNCTION update_timestamp();


CREATE TABLE IF NOT EXISTS outbox (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  processed_at TIMESTAMPTZ,
  topic TEXT NOT NULL,
  table_name TEXT NOT NULL,
  event TEXT NOT NULL DEFAULT CHECK (event IN ('insert', 'update', 'delete')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processed')),
  msg JSONB NOT NULL DEFAULT '{}'::jsonb
);


CREATE INDEX IF EXISTS idx_outbox_created ON outbox (created_at) WHERE status = 'pending';
CREATE INDEX IF EXISTS idx_outbox_processed ON outbox (processed_at) WHERE status = 'processed';


CREATE OR REPLACE FUNCTION record_event()
RETURNS TRIGGER SS
  INSERT INTO outbox (table_name, topic, event, msg)
  VALUES (
    TG_TABLE_NAME,
    'edgedb.event.' + TG_OP,
    TG_OP,
    row_to_json(NEW)::jsonb
  );
  RETURN NEW;
$$ LANGUAGE plpgsql;


CREATE TRIGGER IF NOT EXISTS trg_node_event
AFTER INSERT OR UPDATE OR DELETE ON nodes
FOR EACH ROW EXECUTE FUNCTION record_event();


CREATE TRIGGER IF NOT EXISTS trg_edge_event
AFTER INSERT OR UPDATE OR DELETE ON edges
FOR EACH ROW EXECUTE FUNCTION record_event();
