// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/edges": {
            "get": {
                "description": "Search and return edges.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "edges"
                ],
                "summary": "Search and return edges",
                "parameters": [
                    {
                        "type": "string",
                        "default": "",
                        "description": "search term",
                        "name": "term",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\u003cspan class=\"text-red-500\"\u003e",
                        "description": "snippet start",
                        "name": "snippetStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\u003c/span\u003e",
                        "description": "snippet start",
                        "name": "snippetEnd",
                        "in": "query"
                    },
                    {
                        "maximum": 64,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "snippet tokens",
                        "name": "tokens",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1000,
                        "description": "limit results returned",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of edges",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Edge"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            },
            "put": {
                "description": "Add/update on or more edges.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "edges"
                ],
                "summary": "Add/update one or more edges.",
                "parameters": [
                    {
                        "description": "One or more nodes to add/update",
                        "name": "nodes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.PUTEdgesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of edges",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Edge"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/v1/nodes": {
            "get": {
                "description": "Search and return nodes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Search and return nodes",
                "parameters": [
                    {
                        "type": "string",
                        "default": "",
                        "description": "search term",
                        "name": "term",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\u003cspan class=\"text-red-500\"\u003e",
                        "description": "snippet start",
                        "name": "snippetStart",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\u003c/span\u003e",
                        "description": "snippet start",
                        "name": "snippetEnd",
                        "in": "query"
                    },
                    {
                        "maximum": 64,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "snippet tokens",
                        "name": "tokens",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1000,
                        "description": "limit results returned",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of nodes",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Node"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            },
            "put": {
                "description": "Add/update on or more nodes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Add/update one or more nodes.",
                "parameters": [
                    {
                        "description": "One or more nodes to add/update",
                        "name": "nodes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.PUTNodesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of nodes",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Node"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/api/v1/upload": {
            "put": {
                "description": "Uploads one or more nodes and edges sets.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "Uploads one or more nodes and edges sets.",
                "parameters": [
                    {
                        "description": "One or more nodes to add/update",
                        "name": "nodes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.UploadReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of uploaded nodes and edges",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/server.UploadedResp"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Edge": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "from_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "properties": {
                    "$ref": "#/definitions/models.Properties"
                },
                "snippet": {
                    "description": "this is a special field show a small snippet of the match terms",
                    "type": "string"
                },
                "to_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "models.Node": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "properties": {
                    "$ref": "#/definitions/models.Properties"
                },
                "snippet": {
                    "description": "this is a special field show a small snippet of the match terms",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Properties": {
            "type": "object",
            "additionalProperties": {}
        },
        "server.PUTEdgesReq": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Edge"
                    }
                }
            }
        },
        "server.PUTNodesReq": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Node"
                    }
                }
            }
        },
        "server.UploadReq": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Edge"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Node"
                    }
                }
            }
        },
        "server.UploadedResp": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Edge"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Node"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "EdgeDB API",
	Description:      "EdgeDB API server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
